### ISSUE TITLE
Accessory disappeared although the pluglin finds the lock

### ISSUE THREAD

**Issue by fmanga** [homebridge-plugins/homebridge-august#130]
### Describe Your Problem

I mistakenly deleted the August Lock accessory from my Home using my iPhone. Now, I cannot reinstall it anymore. I tried uninstalling and reinstalling the plugin, but nothing. The accessory is not present in the homebridge accessories either. 

### Relevant log output

```shell
[8/9/2024, 12:38:02 AM] [August] Restarting child bridge...
[8/9/2024, 12:38:02 AM] Got SIGTERM, shutting down child bridge process...
[8/9/2024, 12:38:07 AM] [August] Child bridge process ended
[8/9/2024, 12:38:07 AM] [August] Process Ended. Code: 143, Signal: null
[8/9/2024, 12:38:14 AM] [August] Restarting Process...
[8/9/2024, 12:38:15 AM] [August] Launched child bridge with PID 255994
[8/9/2024, 12:38:16 AM] Registering platform 'homebridge-august.August'
[8/9/2024, 12:38:16 AM] [August] Loaded homebridge-august v2.2.6 child bridge successfully
[8/9/2024, 12:38:16 AM] Loaded 0 cached accessories from cachedAccessories.0EA0F86CDAD5.
[8/9/2024, 12:38:16 AM] Homebridge v1.8.4 (HAP v0.12.2) (August) is running on port 49718.
[8/9/2024, 12:38:17 AM] [August] Total August Locks Found: 1
```

### Device & Model

August WiFi Smart Lock (Gen 4)

### Node.js Version

v20.12.2

### NPM Version

v10.5.0

### Homebridge Version

v1.8.4

### Homebridge August Plugin Version

v2.2.6

### Homebridge Config UI X Plugin Version

v4.56.4

### Operating System

docker

**Comment by fmanga** [comment]
I think this is a more complete plugin log with an error


[8/9/2024, 1:03:47 AM] [August] Child bridge process ended
[8/9/2024, 1:03:47 AM] [August] Process Ended. Code: 1, Signal: null
[8/9/2024, 1:03:54 AM] [August] Restarting Process...
[8/9/2024, 1:03:55 AM] [August] Launched child bridge with PID 532
[8/9/2024, 1:03:56 AM] Registering platform 'homebridge-august.August'
[8/9/2024, 1:03:56 AM] [August] Loaded homebridge-august v2.2.6 child bridge successfully
[8/9/2024, 1:03:56 AM] Loaded 0 cached accessories from cachedAccessories.0EA0F86CDAD5.
Error: listen EADDRINUSE: address already in use :::49718
    at Server.setupListenHandle [as _listen2] (node:net:1897:16)
    at listenInCluster (node:net:1945:12)
    at Server.listen (node:net:2037:7)
    at EventedHTTPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:166:20)
    at HAPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:380:21)
    at Bridge.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1378:18)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
[8/9/2024, 1:03:57 AM] [August] Child bridge process ended
[8/9/2024, 1:03:57 AM] [August] Process Ended. Code: 1, Signal: null
[8/9/2024, 1:04:04 AM] [August] Restarting Process...
[8/9/2024, 1:04:05 AM] [August] Launched child bridge with PID 546
[8/9/2024, 1:04:06 AM] Registering platform 'homebridge-august.August'
[8/9/2024, 1:04:06 AM] [August] Loaded homebridge-august v2.2.6 child bridge successfully
[8/9/2024, 1:04:06 AM] Loaded 0 cached accessories from cachedAccessories.0EA0F86CDAD5.
Error: listen EADDRINUSE: address already in use :::49718
    at Server.setupListenHandle [as _listen2] (node:net:1897:16)
    at listenInCluster (node:net:1945:12)
    at Server.listen (node:net:2037:7)
    at EventedHTTPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:166:20)
    at HAPServer.listen (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:380:21)
    at Bridge.<anonymous> (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1378:18)
    at step (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
[8/9/2024, 1:04:06 AM] [August] Child bridge process ended
[8/9/2024, 1:04:06 AM] [August] Process Ended. Code: 1, Signal: null
[8/9/2024, 1:04:27 AM] [August] Initializing August platform...
[8/9/2024, 1:04:27 AM] Loading 2 accessories...
[8/9/2024, 1:04:28 AM] [August] Total August Locks Found: 1
[8/9/2024, 1:07:37 AM] [August] Initializing August platform...
[8/9/2024, 1:07:37 AM] Loading 2 accessories...
[8/9/2024, 1:07:38 AM] [August] Total August Locks Found: 1

**Comment by fmanga** [comment]
Hi, 
I resolved the issue by resetting the August device. 
Thank you,
Felice

**Comment by fLyRhyTHeMz** [comment]
I’m having the same issue. Plug-in logs shows it finds the locks, but doesn't push them to HomeKit nor does it appear under devices section. 

When you say reset, do you mean factory reset? Or just some other option like pulling batteries.

**Comment by fmanga** [comment]
Hey, what I did was reset the lock from the August app and reinstall it in
HomeKit. After that everything went smoothly.

Best,
FM

**Comment by fLyRhyTHeMz** [comment]
Ah I see. It seems like we had different issues then. Mine was related more to the fact that my locks already had HomeKit built in and therefore would not display, but HomeKit on August lock gen 4 is notoriously bad. 

I case anyone else comes upon this, the solution was to turn on debug logging in the plugin and grab the lock id from the logs and override the HomeKit setting in the plugin config for each lock. All is working now.
