### ISSUE TITLE
Errors after migration to new host device

### ISSUE THREAD

**Issue by dacarson** [homebridge-plugins/homebridge-august#86]
### Describe The Bug

I migrated my HomeBridge from one RPi to another RPi and now HB won't startup. Was working fine before. I tried deleting all the configuration information but I still get the error.

### To Reproduce

Backup HB, restore HB on a new device

### Expected behavior

HB be able to startup and August Lock plugin to continue working

### Relevant log output

```shell
[30/12/2023, 12:42:26] [August] Initializing August platform...
[30/12/2023, 12:42:26] [August] Platform Config: {"logging":"standard"}
[30/12/2023, 12:42:26] [B-Hyve] Initializing bhyve platform...
[30/12/2023, 12:42:26] [B-Hyve] Starting Orbit Platform using homebridge API 2.7
[30/12/2023, 12:42:26] [B-Hyve] Getting Account info...
[30/12/2023, 12:42:26] [August] Input Your August email verification code into the validateCode config and restart Homebridge.
FetchError: Status 429 (undefined): undefined
[30/12/2023, 12:42:26] TypeError: Cannot read properties of undefined (reading 'x-august-access-token')
    at August.session (/var/lib/homebridge/node_modules/homebridge-august/node_modules/august-api/src/util/session.js:28:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at August.#start (/var/lib/homebridge/node_modules/homebridge-august/node_modules/august-api/src/index.js:49:19)
    at August.authorize (/var/lib/homebridge/node_modules/homebridge-august/node_modules/august-api/src/methods/authorize.js:9:13)
[30/12/2023, 12:42:26] Got SIGTERM, shutting down Homebridge...
```

### Config for homebridge-august

```shell
{
            "name": "August",
            "credentials": {
                "augustId": "my personal email@gmail.com",
                "password": "my august password",
                "isValidated": false,
                "notice": "Keep your tokens a secret!",
                "installId": "bcade58e-5b96-4003-91b6-fc2242460185"
            },
            "options": {
                "logging": "standard"
            },
            "platform": "August"
        },
```

### Device & Model

Unsure of model of August locks - though I have two

### Node.js Version

v20.10.0

### NPM Version

v10.2.3

### Homebridge Version

Homebridge v1.7.0 (HAP v0.11.1)

### Homebridge August Plugin Version

v1.3.3

### Operating System

Debian GNU/Linux 12 (bookworm) [64 bit]

**Comment by dacarson** [comment]
Suspect this to be a dup of:
https://github.com/hufftheweevil/august-api/issues/3

**Comment by rnikoopour** [comment]
Having this same issue with a single August lock.  I did recently migrate to a new host, but I'm not sure it's really related to that.  This is resulting in homebridge endlessly restarting itself.

I uninstalled and reinstalled the plugin.  This resulted in a fresh configuration that was still exhibiting this behavior.

**Comment by dacarson** [comment]
The issue is that there are rate limits on the August API, and you get this error when you hit it. 
Wait till tomorrow and it should go away by itself. It did for me.
If you see this line in your logs, it is the rate limit issue:
`FetchError: Status 429 (undefined): undefined`

**Comment by rnikoopour** [comment]
Waiting over night worked.  Thanks for the tip!
